<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="icon" href="/favicon.ico">

    <title>Paramatma</title>

    <?php $this->assets->outputCss('cssHeader') ?>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <?php $this->assets->outputJs('jsHeader') ?>
</head>
<body>

<!-- Fixed navbar -->
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a id="logo-link" class="navbar-brand" href="/">Paramatma</a>
        </div>

        <div class="navbar-collapse collapse">
            <form id="search-form-top" class="navbar-form navbar-right">
                <input type="text" placeholder="Search..." class="form-control search">
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/download"><i class="fa fa-download"></i>&nbsp;&nbsp;Download</a></li>
                <li><a href="http://modules.paramatma.io"><i class="fa fa-cogs"></i>&nbsp;&nbsp;Modules</a></li>
                <li><a href="http://themes.paramatma.io"><i class="fa fa-diamond"></i>&nbsp;&nbsp;Themes</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-users"></i>&nbsp;&nbsp;Community <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="/community"><i class="fa fa-hand-grab-o"></i>&nbsp;&nbsp;Get Involved</a></li>
                        <li><a href="http://forum.paramatma.io"><i class="fa fa-comments"></i>&nbsp;&nbsp;Forum</a></li>
                        <li><a href="http://stackoverflow.com/questions/tagged/paramatma"><i class="fa fa-stack-overflow"></i>&nbsp;&nbsp;Stack Overflow</a></li>
                        <li><a href="https://github.com/paramatma-io/paramatma"><i class="fa fa-github-alt"></i>&nbsp;&nbsp;GitHub</a></li>
                        <li><a href="https://github.com/paramatma-io/paramatma/issues"><i class="fa fa-info"></i>&nbsp;&nbsp;Issue Tracker</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-graduation-cap"></i>&nbsp;&nbsp;Learn <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="http://docs.paramatma.io/en/latest/quickstart.html">Quick Start Guide</a></li>
                        <li><a href="http://docs.paramatma.io/en/latest/index.html">Documentation</a></li>
                        <li><a href="http://docs.paramatma.io/en/latest/tutorials.html">Tutorials</a></li>
                    </ul>
                </li>
                <li><a href="http://blog.paramatma.io">Blog</a></li>
                <li><a href="/about">About</a></li>
                <li class="dropdown">
                    <a href="javascript:void" class="dropdown-toggle" data-toggle="dropdown" id="select-language-link">
                        |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="/themes/default/img/flags_iso/24/gb.png" alt="English"/> <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li>
                            <a href="javascript:void" id="select-language-link">
                                <img src="/themes/default/img/flags_iso/24/ru.png" alt="Русский"/> Русский
                            </a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="javascript:void" id="search-form-top-link"><i class="fa fa-search fa-lg"></i></a>
                </li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>

<?php echo $this->getContent() ?>

<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-xs-4 col-sm-3">
                <h4>Download</h4>
                <ul>
                    <li><a href="/download">Installing Phalcon PHP</a></li>
                    <li><a target="_blank" class="header-nav-link" href="http://docs.phalconphp.com/en/latest/index.html">Documentation</a></li>
                    <li><a href="http://api.phalconphp.com">API</a></li>
                    <li><a href="http://docs.phalconphp.com/en/latest/reference/tutorial.html">Tutorial</a></li>
                    <li><a href="http://docs.phalconphp.com/en/latest/reference/tutorial.html#sample-applications">Sample applications</a></li>
                </ul>
            </div>
            <div class="col-xs-4 col-sm-3">
                <h4>Community</h4>
                <ul>
                    <li><a target="_blank" class="header-nav-link" href="http://forum.phalconphp.com/">Forum</a></li>
                    <li><a href="https://github.com/phalcon/cphalcon">GitHub</a></li>
                    <li><a href="https://github.com/phalcon/cphalcon/issues">Issue Tracker</a></li>
                    <li><a href="http://stackoverflow.com/questions/tagged/phalcon">Stack Overflow</a></li>
                    <li><a href="/en/testimonials">Testimonials</a></li>
                    <li><a href="http://builtwith.phalconphp.com/">Built with Phalcon</a></li>
                    <li><a href="http://store.phalconphp.com/">Store</a></li>
                </ul>
            </div>
            <div class="col-xs-4 col-sm-2">
                <h4>About</h4>
                <ul>
                    <li><a href="http://blog.phalconphp.com/" class="link-black">Blog</a></li>
                    <li><a href="/en/about">About</a></li>
                    <li><a href="/en/team">Team</a></li>
                    <li><a href="/en/roadmap">Roadmap</a></li>
                    <li><a href="/en/donate">Donate</a></li>
                    <li><a href="/en/consulting">Consulting</a></li>
                    <li><a href="/en/hosting">Hosting</a></li>
                </ul>
            </div>
            <div class="visible-xs" id="dedication-spacer"></div>
            <div class="col-xs-12 col-sm-4" id="license-wrapper">
                <div class="dedication">
                    <h4>Paramatma is inspired by and<br>dedicated to:</h4>
                    <img src="/themes/default/img/sri-hari.png" alt="Sri Hari"/>
                </div>
            </div>
        </div>
    </div>
</footer>

<?php $this->assets->outputJs('jsFooter') ?>
</body>
</html>
