<div id="home-hero">
    <video id="hero-video-bg" loop="" poster="/themes/default/img/stars-bg.jpg">
        <source src="http://totaltheme.wpengine.com/wp-content/uploads/assets/among_the_stars.webm" type="video/webm">
        <source src="http://totaltheme.wpengine.com/base/wp-content/uploads/sites/7/among_the_stars.mp4" type="video/mp4">
    </video>

    <div id="home-hero-content">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-lg-6 col-md-6">
                    <div class="well dark">
                        <h1>Paramatma CMS</h1>
                        <p id="hero-about">
                            Is an advanced open-source CMF/CMS built for high load projects. High performance,
                            uber security, total flexibility &mdash; the reasons you'll love Paramatma.
                            It is based on a blazing fast <a target="_blank" href="http://phalconphp.com">Phalcon</a>
                            PHP framework which is built as a C-extension. Paramatma is available under the
                            <a target="_blank" href="http://opensource.org/licenses/MIT">MIT License</a>.
                        </p>
                        <a href="http://demo.paramatma.io" class="btn btn-info btn-lg"><span class="btn-label"><i class="fa fa-hand-spock-o"></i>&nbsp;Demo</span></a>&nbsp;&nbsp;&nbsp;
                        <a href="/download" class="btn btn-primary btn-lg"><span class="btn-label"><i class="fa fa-download"></i>&nbsp;Download</span></a>&nbsp;&nbsp;&nbsp;
                        <div class="visible-xs buttons-spacer"></div>
                        <a href="http://docs.paramatma.io/en/latest/quickstart.html" class="btn btn-lg btn-warning"><span class="btn-label">Quick Start</span></a>
                    </div>
                </div>
                <div class="col-sm-12 col-lg-6 col-md-6"></div>
            </div>
        </div>
    </div>

    <div id="hero-img">&nbsp;</div>
</div>
<div class="subhero-panel">Please support Paramatma development by donating via <a href="#">PayPal</a>, <a
        href="#">Plegie</a> or <a href="#">Flattr</a></div>

<div id="main-content-wrapper">
    <div class="container">
        <div class="jumbotron codesamples">
            <h1>Paramatma features</h1>

            <p>
                <ul class="features features-positive">
                    <li>C-extensions are loaded together with PHP one time on the web server’s daemon start process</li>
                    <li>Classes and functions provided by the extension are ready to use for any application</li>
                    <li>The code is compiled and isn’t interpreted because is already compiled to a specific platform and processor</li>
                    <li>Thanks to its low-level architecture and optimizations <strong>Phalcon provides the lowest overhead for MVC-based applications</strong></li>
                </ul>
            </p>

            <p><a class="btn btn-primary btn-lg">Learn more</a></p>
        </div>
    </div>
</div>


